def rootPath  = "./deployments"
def shellPath  = "./build.sh"
def gitUrl = "http://192.168.126.25/git/cbb/logfv.git"
def branch = "master"
def credentialsId = "c078ac92-89dd-4842-8292-5e348e68db08"
def repositories = "192.168.126.19:85/logfv/"
def auth = "admin:Sipsd@123"
def tag = "logfv:latest"
def deleteUrl = "http://192.168.126.19:85/api/repositories/logfv/logfv/tags/latest"
def remoteHost="192.168.126.16"
def remoteUser="root"
def remotePwd="kjjsyf#1314"
def containerName = "logfv-app"
def dockerCompose = "/home/soft/logfv.yml"
def robot = "360ac2ce-efe5-4478-8703-7cd3bd463044"
pipeline {
    agent any
    stages {
        stage('拉取代码') {
            steps {
                git branch: "$branch", credentialsId: "$credentialsId", url: "$gitUrl"
            }
        }
        stage('镜像构建'){
            steps {
                script {
                    sh "cd $rootPath && chmod a+x $shellPath && sh $shellPath"
                }
            }
        }
        stage('镜像推送到远程仓库'){
            steps {
                script {
                        echo "删除远程${tag}镜像"
                        sh "curl --user $auth  -X DELETE $deleteUrl"
                        echo "推送镜像到远程仓库"
                        sh "docker tag $tag $repositories$tag"
                        sh "docker push $repositories$tag"
                        echo "删除本地${tag}镜像"
                        sh "docker rmi $repositories$tag"
                    }
                }
        }
        stage('远程启动容器') {
             steps {
                 script
                    {
                        stage ('启动容器') {
                               def remote = [:]
                               remote.name = 'remote'
                               remote.host = remoteHost
                               remote.user = remoteUser
                               remote.password = remotePwd
                               remote.allowAnyHosts= true
                               sshCommand remote: remote,command: "docker stop $containerName"
                               sshCommand remote: remote,command: "docker rm $containerName"
                               sshCommand remote: remote,command: "docker rmi $repositories$tag"
                               sshCommand remote: remote,command: "docker-compose -f $dockerCompose up -d"
                        }
                    }

             }
        }
    }
//     post {
//         success {
//             dingtalk(robot: '360ac2ce-efe5-4478-8703-7cd3bd463044',
//             type: 'ACTION_CARD',
//             at: [],
//             atAll: false,
//             title: '沃壤前端日志工具',
//             text: [
//             "* 项目名称：沃壤赋能平台前端日志工具",
//             "* 任务：#${BUILD_NUMBER}",
//             "* 状态：<font color=#00EE00 >成功</font>",
//             "* 持续时间：${currentBuild.durationString}".split("and counting")[0],
//             "* 执行人：${currentBuild.buildCauses.shortDescription}",
//             ],
//             messageUrl: '',
//             picUrl: '',
//             singleTitle: '',
//             btns: [],
//             btnLayout: 'H',
//             hideAvatar: false
//             )
//         }
//         failure {
//             dingtalk(robot: '360ac2ce-efe5-4478-8703-7cd3bd463044',
//             type: 'ACTION_CARD',
//             at: [],
//             atAll: false,
//             title: '沃壤前端日志工具',
//             text: [
//             "* 项目名称：沃壤赋能平台前端日志工具",
//             "* 任务：#${BUILD_NUMBER}",
//             "* 状态：<font color=#EE0000 >失败</font>",
//             "* 持续时间：${currentBuild.durationString}".split("and counting")[0],
//             "* 执行人：${currentBuild.buildCauses.shortDescription}",
//             ],
//             messageUrl: '',
//             picUrl: '',
//             singleTitle: '',
//             btnLayout: 'H',
//             hideAvatar: false
//             )
//         }
//     }
}
