pipeline {
    agent any
    stages {
        stage('拉取代码') {
            steps {
                git branch: 'master', credentialsId: 'c078ac92-89dd-4842-8292-5e348e68db08', url: 'http://192.168.126.25/git/scri/our-dev-group/logfv.git'
            }
        }
        stage('镜像构建'){
            steps {
                sh "cd ./deployments && chmod a+x ./build.sh && sh ./build.sh"
            }
        }
        stage('镜像推送到远程仓库'){
            steps {
                    echo "删除远程logfv:latest镜像"
                    sh "curl --user admin:Sipsd@123  -X DELETE http://192.168.126.19:85/api/repositories/logfv/logfv/tags/latest"
                    echo "推送镜像到远程仓库"
                    sh "docker tag logfv:latest 192.168.126.19:85/logfv/logfv:latest"
                    sh "docker push 192.168.126.19:85/logfv/logfv:latest"
                    echo "删除本地logfv:latest镜像"
                    sh "docker rmi 192.168.126.19:85/logfv/logfv:latest"
                }
        }
        stage('远程启动容器') {
             steps {
                 script
                    {
                        sh """ssh -tt root@192.168.126.16 << EOF
                            docker stop logfv-app
                            docker rm logfv-app
                            docker rmi 192.168.126.19:85/logfv/logfv:latest
                            docker-compose -f /home/soft/logfv.yml up -d
                            exit
                            EOF"""
                    }

             }
        }
    }
    post {
        success {
            dingtalk(robot: '360ac2ce-efe5-4478-8703-7cd3bd463044',
            type: 'ACTION_CARD',
            at: [],
            atAll: false,
            title: '沃壤前端日志系统',
            text: ["项目名称：沃壤赋能平台前端日志系统","任务：#56","状态：成功","持续时间：14 秒","执行人：Started by GitLab push by 粟宣艳"],
            messageUrl: '',
            picUrl: '',
            singleTitle: '',
            btns: [],
            btnLayout: '',
            hideAvatar: false
            )
        }
    }
}
